#!/bin/sh

. ~/bin/shcomm.sh

MYADDRESSBOOK="$HOME/addressbook"

remove_colon() {
	echo "$@" | tr ':' ' '
}

if [ $# -lt 1 ]; then
	# interactive mode
	stty erase ''
	promptRESPONSE "Account:    "
	ACCOUNT="$RESPONSE"
	promptRESPONSE "Name:       "
	NAME="$RESPONSE"
	printf         "Email:      ? "
	read EMAIL
	printf         "Phone:      ? "
	read PHONE
else
	USAGE="`basename $0` [-a account][-n name][-e email][-p phone]"
	while getopts 'a:n:e:p:h' OPTION; do
		case "$OPTION" in
			a) ACCOUNT="$OPTARG";;
			e) EMAIL="$OPTARG";;
			n) NAME="$OPTARG";;
			p) PHONE="$OPTARG";;
			\?|h) printUSAGE "$USAGE";;
		esac
	done
	if [ -z "$ACCOUNT" -o -z "$NAME" ]; then
		printERROR "Account and Name cannot be empty."
		exit 1
	fi
fi

ACCOUNT="`remove_colon "$ACCOUNT"`"
NAME="`remove_colon "$NAME"`"
EMAIL="`remove_colon "$EMAIL"`"
PHONE="`remove_colon "$PHONE"`"

echo "$ACCOUNT:$NAME:$EMAIL:$PHONE" >> "$MYADDRESSBOOK"
